# Generated by Django 5.1.3 on 2025-02-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_plan_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
