# Generated by Django 5.1.3 on 2024-11-29 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('profissional', 'Profissional Liberal'), ('empresa', 'Empresa')], max_length=15)),
                ('foto_logo', models.ImageField(blank=True, null=True, upload_to='uploads/fotos_perfil/')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('endereco', models.JSONField()),
                ('telefone', models.CharField(max_length=15)),
                ('area_atuacao', models.CharField(max_length=200)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('certificados', models.FileField(blank=True, null=True, upload_to='uploads/certificados/')),
                ('registros_profissionais', models.FileField(blank=True, null=True, upload_to='uploads/registros_profissionais/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
