# Generated by Django 5.1.3 on 2024-12-16 14:02

import perfil_profissional.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil_profissional', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilprofissional',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[perfil_profissional.models.PerfilProfissional.validate_cpf]),
        ),
    ]
