# Generated by Django 5.1.3 on 2025-01-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil_profissional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilprofissional',
            name='tipo',
            field=models.CharField(choices=[('professional', 'Profissional Liberal'), ('company', 'Empresa')], default='professional', editable=False, max_length=20),
        ),
    ]
