# Generated by Django 5.1.3 on 2024-12-17 00:27

import perfil_profissional.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil_profissional', '0002_alter_perfilprofissional_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilprofissional',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='perfilprofissional',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[perfil_profissional.models.PerfilProfissional.validate_cpf]),
        ),
    ]
