# Generated by Django 5.1.3 on 2025-01-21 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfil_profissional', '0002_perfilprofissional_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prazo_execucao', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('assinatura', 'Em Assinatura'), ('concluido', 'Concluído'), ('arquivado', 'Arquivado')], default='pendente', max_length=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('contrato_gerado', models.FileField(blank=True, null=True, upload_to='contratos/gerados/')),
                ('contrato_assinado', models.FileField(blank=True, null=True, upload_to='contratos/assinados/')),
                ('contratado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_contratado', to='perfil_profissional.perfilprofissional')),
                ('contratante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_contratante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
